version: "3"

services:
  postgres:
    image: postgis/postgis
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@wb-fernstudium.de
      - PGADMIN_DEFAULT_PASSWORD=secret
    volumes:
      - pgadmin-config:/var/lib/pgadmin/

volumes:
  postgres-data:
  pgadmin-config: